# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MyFinanceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFinanceApp
  pod 'SwiftGen', '~> 6.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'DTTableViewManager'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RealmSwift'

end
